/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_dyn_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};

/* f_dyn:(i0[4],i1[4],i2[2])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=7.5000000000000000e-01;
  a01=3.9000000000000001e-01;
  a02=arg[0]? arg[0][1] : 0;
  a03=cos(a02);
  a01=(a01*a03);
  a00=(a00+a01);
  a01=2.;
  a03=3.3600000000000002e-01;
  a04=arg[0]? arg[0][2] : 0;
  a05=(a03*a04);
  a06=1.2600000000000000e-01;
  a07=arg[0]? arg[0][3] : 0;
  a08=(a06*a07);
  a05=(a05+a08);
  a05=(a01*a05);
  a08=sin(a02);
  a05=(a05*a08);
  a00=(a00-a05);
  a05=casadi_sq(a00);
  a08=3.0299999999999999e-01;
  a09=1.9500000000000001e-01;
  a10=cos(a02);
  a10=(a09*a10);
  a10=(a08+a10);
  a11=(a03*a04);
  a12=(a06*a07);
  a11=(a11+a12);
  a12=sin(a02);
  a11=(a11*a12);
  a10=(a10-a11);
  a11=casadi_sq(a10);
  a05=(a05+a11);
  a11=cos(a02);
  a11=(a03*a11);
  a12=casadi_sq(a11);
  a05=(a05+a12);
  a12=cos(a02);
  a12=(a06*a12);
  a13=casadi_sq(a12);
  a05=(a05+a13);
  a05=sqrt(a05);
  a00=(a00/a05);
  a13=arg[2]? arg[2][0] : 0;
  a14=arg[1]? arg[1][0] : 0;
  a15=(a01*a14);
  a16=arg[1]? arg[1][1] : 0;
  a15=(a15*a16);
  a17=casadi_sq(a16);
  a15=(a15+a17);
  a17=sin(a02);
  a17=(a09*a17);
  a18=(a03*a04);
  a19=(a06*a07);
  a18=(a18+a19);
  a19=cos(a02);
  a18=(a18*a19);
  a17=(a17+a18);
  a15=(a15*a17);
  a16=(a14+a16);
  a01=(a01*a16);
  a16=arg[1]? arg[1][2] : 0;
  a17=(a03*a16);
  a18=arg[1]? arg[1][3] : 0;
  a19=(a06*a18);
  a17=(a17+a19);
  a01=(a01*a17);
  a17=sin(a02);
  a01=(a01*a17);
  a15=(a15+a01);
  a13=(a13+a15);
  a15=(a00*a13);
  a01=(a10/a05);
  a17=arg[2]? arg[2][1] : 0;
  a19=casadi_sq(a14);
  a20=sin(a02);
  a09=(a09*a20);
  a20=(a03*a04);
  a21=(a06*a07);
  a20=(a20+a21);
  a21=cos(a02);
  a20=(a20*a21);
  a09=(a09+a20);
  a19=(a19*a09);
  a19=(a17-a19);
  a09=(a01*a19);
  a15=(a15+a09);
  a09=(a11/a05);
  a20=5.7400000000000002e+00;
  a20=(a20*a17);
  a21=casadi_sq(a14);
  a03=(a03*a21);
  a21=sin(a02);
  a03=(a03*a21);
  a20=(a20-a03);
  a03=8.7802590536285777e+02;
  a03=(a03*a04);
  a20=(a20-a03);
  a03=4.1484102672122507e+00;
  a03=(a03*a16);
  a20=(a20-a03);
  a03=(a09*a20);
  a15=(a15+a03);
  a03=(a12/a05);
  a16=1.1640000000000001e+01;
  a16=(a16*a17);
  a14=casadi_sq(a14);
  a06=(a06*a14);
  a02=sin(a02);
  a06=(a06*a02);
  a16=(a16-a06);
  a06=8.1805607692649692e+03;
  a06=(a06*a07);
  a16=(a16-a06);
  a06=5.4267871498110081e+00;
  a06=(a06*a18);
  a16=(a16-a06);
  a06=(a03*a16);
  a15=(a15+a06);
  a06=(a12*a00);
  a06=(a06+a03);
  a18=(a06*a00);
  a12=(a12-a18);
  a18=(a10*a00);
  a07=(a08*a01);
  a18=(a18+a07);
  a07=(a18*a00);
  a10=(a10-a07);
  a07=casadi_sq(a10);
  a02=(a18*a01);
  a08=(a08-a02);
  a02=casadi_sq(a08);
  a07=(a07+a02);
  a02=(a18*a09);
  a14=casadi_sq(a02);
  a07=(a07+a14);
  a14=(a18*a03);
  a17=casadi_sq(a14);
  a07=(a07+a17);
  a07=sqrt(a07);
  a10=(a10/a07);
  a17=(a12*a10);
  a04=(a06*a01);
  a08=(a08/a07);
  a21=(a04*a08);
  a17=(a17-a21);
  a21=(a06*a09);
  a02=(a02/a07);
  a22=(a21*a02);
  a17=(a17+a22);
  a22=1.;
  a23=(a06*a03);
  a23=(a22-a23);
  a14=(a14/a07);
  a24=(a23*a14);
  a17=(a17-a24);
  a24=(a17*a10);
  a12=(a12-a24);
  a24=(a11*a00);
  a24=(a24+a09);
  a00=(a24*a00);
  a11=(a11-a00);
  a00=(a11*a10);
  a01=(a24*a01);
  a25=(a01*a08);
  a00=(a00-a25);
  a09=(a24*a09);
  a22=(a22-a09);
  a09=(a22*a02);
  a00=(a00-a09);
  a03=(a24*a03);
  a09=(a03*a14);
  a00=(a00+a09);
  a09=(a00*a10);
  a11=(a11-a09);
  a09=casadi_sq(a11);
  a25=(a00*a08);
  a01=(a01+a25);
  a25=casadi_sq(a01);
  a09=(a09+a25);
  a25=(a00*a02);
  a22=(a22+a25);
  a25=casadi_sq(a22);
  a09=(a09+a25);
  a25=(a00*a14);
  a25=(a25-a03);
  a03=casadi_sq(a25);
  a09=(a09+a03);
  a09=sqrt(a09);
  a11=(a11/a09);
  a03=(a12*a11);
  a26=(a17*a08);
  a04=(a04+a26);
  a01=(a01/a09);
  a26=(a04*a01);
  a03=(a03+a26);
  a26=(a17*a02);
  a26=(a26-a21);
  a22=(a22/a09);
  a21=(a26*a22);
  a03=(a03+a21);
  a21=(a17*a14);
  a23=(a23+a21);
  a25=(a25/a09);
  a21=(a23*a25);
  a03=(a03+a21);
  a21=(a03*a11);
  a12=(a12-a21);
  a21=casadi_sq(a12);
  a27=(a03*a01);
  a27=(a27-a04);
  a04=casadi_sq(a27);
  a21=(a21+a04);
  a04=(a03*a22);
  a26=(a26-a04);
  a04=casadi_sq(a26);
  a21=(a21+a04);
  a04=(a03*a25);
  a23=(a23-a04);
  a04=casadi_sq(a23);
  a21=(a21+a04);
  a21=sqrt(a21);
  a12=(a12/a21);
  a12=(a12*a13);
  a27=(a27/a21);
  a27=(a27*a19);
  a12=(a12+a27);
  a26=(a26/a21);
  a26=(a26*a20);
  a12=(a12+a26);
  a23=(a23/a21);
  a23=(a23*a16);
  a12=(a12+a23);
  a12=(a12/a21);
  a06=(a06*a12);
  a15=(a15-a06);
  a11=(a11*a13);
  a01=(a01*a19);
  a11=(a11-a01);
  a22=(a22*a20);
  a11=(a11+a22);
  a25=(a25*a16);
  a11=(a11+a25);
  a03=(a03*a12);
  a11=(a11-a03);
  a11=(a11/a09);
  a24=(a24*a11);
  a15=(a15-a24);
  a10=(a10*a13);
  a08=(a08*a19);
  a10=(a10+a08);
  a02=(a02*a20);
  a10=(a10-a02);
  a14=(a14*a16);
  a10=(a10-a14);
  a17=(a17*a12);
  a10=(a10-a17);
  a00=(a00*a11);
  a10=(a10-a00);
  a10=(a10/a07);
  a18=(a18*a10);
  a15=(a15-a18);
  a15=(a15/a05);
  if (res[0]!=0) res[0][0]=a15;
  if (res[0]!=0) res[0][1]=a10;
  if (res[0]!=0) res[0][2]=a11;
  if (res[0]!=0) res[0][3]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_dyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_dyn_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_dyn_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_dyn_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_dyn_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_dyn_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_dyn_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_dyn_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_dyn_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f_dyn_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_dyn_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_dyn_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_dyn_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_dyn_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_dyn_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_dyn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_dyn_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_dyn(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[42];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_dyn\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_dyn\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s2, w+14);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+4, casadi_s2, w+14);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+8, casadi_s3, w+14);
  --resc;
  res[0] = w+10;
  f_dyn_incref();
  mem = f_dyn_checkout();
  i = f_dyn(arg, res, iw, w+14, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_dyn\" failed.");
  f_dyn_release(mem);
  f_dyn_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif

casadi_int main_f_dyn(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[42];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+4;
  arg[2] = w+8;
  res[0] = w+10;
  a = w;
  for (j=0; j<10; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_dyn(arg, res, iw, w+14, 0);
  if (flag) return flag;
  r = w+10;
  for (j=0; j<4; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_dyn(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_dyn")==0) {
    mex_f_dyn(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_dyn'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_dyn")==0) {
    return main_f_dyn(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_dyn'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
